- block:
    - name: "Install secrets integration"
      shell: "argocd --plaintext app sync sealed-secrets --prune"
      retries: 25
      delay: 3
      register: vault_sync
      until: vault_sync.rc == 0

    - name: Save certificate to temporary directory
      shell: "curl -vvv \"http://$(kubectl get service/sealed-secrets -n vault -o jsonpath='{.spec.clusterIP}'):8080/v1/cert.pem\" -o /etc/rancher/k3s/sealed-secrets.cert.pem"
      retries: 25
      delay: 3
      register: vault_sync
      until: vault_sync.rc == 0

    - name: Fetch certificate
      fetch:
          src: "/etc/rancher/k3s/sealed-secrets.cert.pem"
          dest: "artifacts/sealed-secrets.cert.pem"
          flat: true

  environment:
      KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  become: yes
  become_user: root
