- name: Make sure /etc/riotkit directory exists
  become: yes
  become_user: root
  file:
      path: /etc/riotkit
      state: directory
      mode: "u+rw,g-r,o-r"
      owner: root
      group: root

- name: Create alternative resolv.conf
  become: yes
  become_user: root
  template:
      src: etc/resolv.conf
      dest: /etc/riotkit/resolv.conf

- name: Check if k3s is already installed
  register: k3s_installed
  stat:
      path: /etc/rancher/node/password

- name: Add primary node token
  become: yes
  become_user: root
  template:
      src: artifacts/primary-token
      dest: /etc/riotkit/primary-token
      mode: "u+rw,g-r,o-r"
      owner: root
      group: root

- name: Instal K3S compute node from get.k3s.io
  become: yes
  shell: |
      export INSTALL_K3S_VERSION="{{ k3s_version }}";
      {%- if vpn_enabled %}
      export K3S_URL="https://{{ vpn_primary_node_ip }}:6443";
      {%- else %}
      export K3S_URL="https://{{ primary_node_public_ip }}:6443";
      {%- endif %}
      export K3S_TOKEN_FILE="/etc/riotkit/primary-token";
      curl -sfL https://get.k3s.io | bash -s - \
          --node-name="{{ node_type | trim }}" \
          --node-external-ip={{ node_external_ip | default(ansible_ssh_host) }} \
          {%- if node_internal_ip %}
          --node-ip={{ node_internal_ip | trim }} \
          {%- endif %} \
          --node-label="node-type={{ node_type | trim }}" \
          {%- for label in node_labels %}
          --node-label="{{ label | trim }}" \
          {%- endfor %}
          --node-label="node-instance-title={{ node_instance_title | default(inventory_hostname) | trim }}" \
          {%- for taint in node_taints %}
          --node-taint="{{ taint | trim }}" \
          {%- endfor %}
          {%- if noschedule_on_primary %}
          --node-taint="node-role.kubernetes.io/master" \
          {%- endif %}
          --resolv-conf="/etc/riotkit/resolv.conf" \
          --token-file="/etc/riotkit/primary-token" \
          {%- if vpn_enabled %}
          --flannel-iface={{ flannel_iface }} \
          --server="https://{{ vpn_primary_node_ip | trim }}:6443" \
          {%- else %}
          --server="https://{{ primary_node_public_ip | trim }}:6443" \
          {%- endif %}
          {%- for arg in kubelet_args %}
          --kubelet-arg="{{ arg | trim }}" \
          {%- endfor %}
          --kube-apiserver-arg="enable-admission-plugins=NodeRestriction,PodSecurityPolicy,ServiceAccount" \
          --protect-kernel-defaults \
          --with-node-id
  when: not k3s_installed.stat.exists or force_k3s_upgrade

- name: Add a script to allow forced agent node restart with proper clean up
  become: yes
  become_user: root
  template:
      src: usr/local/bin/k3s-force-restart.sh
      dst: /usr/local/bin/k3s-force-restart.sh
      mode: u+rwx,g+rx,o+rx

- name: Enable k3s at system startup
  become: yes
  become_user: root
  systemd:
      name: k3s-agent
      enabled: true
