- include: tools.yaml
  tags: tools

- include: cluster.primary.yaml
  tags: ['cluster', 'k3s']
  when: node_type == "primary"

- include: cluster.compute.yaml
  tags: ['cluster', 'k3s']
  when: node_type != "primary"

- include: sealed_secrets.yaml
  tags: sealed_secrets
  when: node_type == "primary" and secrets_enabled

- include: network-policies.yaml
  tags: network_policies
  when: node_type == "primary" and canal_enabled

- include: repository.yaml
  tags: repository
  when: node_type == "primary"

- include: argocd.yaml
  tags: argocd
  when: node_type == "primary"

- include: firewall.yaml
  tags: firewall
  when: firewall_enabled

- include: firewall.primary.yaml
  tags: firewall
  when: node_type == "primary" and firewall_enabled
