- include: tools.yaml
  tags: tools

- include: system.yaml
  tags: system

- include: go.yaml
  tags: ['go']

- include: shims.yaml
  tags: ['gvisor', 'shims', 'containerd', 'crun']

- include: networking.admin-vpn.yaml
  tags: ['admin-vpn', 'admin_vpn']
  when: admin_vpn_enabled

- include: cluster.primary.yaml
  tags: ['cluster', 'k3s']
  when: node_type == "primary"

- include: cluster.compute.yaml
  tags: ['cluster', 'k3s']
  when: node_type != "primary"

- include: firewall.yaml
  tags: firewall
  when: firewall_enabled
