- become: yes
  become_user: root
  environment:
      KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  block:
      - name: Install Cancal Network Policies
        shell: |
            kubectl apply -f https://projectcalico.docs.tigera.io/manifests/canal.yaml
