- become: yes
  become_user: root
  environment:
      KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  block:
    - name: Add Cilium Helm repository
      kubernetes.core.helm_repository:
          name: cilium
          repo_url: "https://helm.cilium.io/"
          context: "/etc/rancher/k3s/k3s.yaml"

    - name: Deploy Cilium from a Helm Chart
      kubernetes.core.helm:
          name: cilium
          chart_ref: cilium/cilium
          release_namespace: cilium
          create_namespace: true
          context: "/etc/rancher/k3s/k3s.yaml"
          wait: true
          values:
              operator.replicas: "1"
              encryption.type: "wireguard"

    - name: Restart Pods
      shell: "kubectl get pods --all-namespaces -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,HOSTNETWORK:.spec.hostNetwork --no-headers=true | grep '<none>' | awk '{print \"-n \"$1\" \"$2}' | xargs -L 1 -r kubectl delete pod"
