- name: Check if SMTP gateway was already configred
  stat: path=/tmp/git-repository/definitions/infrastructure/smtp.yaml.j2
  register: smtp_configured

- when: '"git_smtp" in ansible_run_tags or not smtp_configured.stat.exists'
  block:
      - name: Create SMTP gateway definition
        template:
            src: "repository/{{ item }}"
            dest: /tmp/git-repository/{{ item | regex_replace('\.j2$', '') }}
        with_items:
            - definitions/infrastructure/smtp.yaml.j2
