

- block:
    - include_tasks: includes/git-clone.yaml
      tags: ['git', 'git_all']

    - name: Prepare git identity
      tags: ['git', 'git_all']
      shell: "cd /tmp/git-repository; git config --local user.name 'Ansible @ Riotkit Role'; git config --local user.email 'example@example.org'"

    - name: Create directories
      tags: ['git', 'git_all']
      file:
          dest: "/tmp/git-repository/{{ item }}"
          state: directory
      with_items:
          - src
          - src/argocd
          - bootstrap/argocd
          - definitions
          - definitions/infrastructure
          - definitions/applications

    - include: repository.argocd.yaml
      tags: ['git_argocd', 'git_all']

    - include: repository.projects.yaml
      tags: ['git_projects', 'git_all']

    - include: repository.infracheck.yaml
      tags: ['git_infracheck', 'git_all']
      when: infracheck_enabled

    - include: repository.smtp.yaml
      tags: ['git_smtp', 'git_all']
      when: mail_enabled

    - include: repository.readme.yaml
      tags: ['git_all']

    - name: Commit changes
      tags: ['git', 'git_all']
      shell: "cd /tmp/git-repository && git add . && git status && git commit -m 'k3s-riotkit update' || true"

    - name: Push changes
      tags: ['git', 'git_all']
      shell: "cd /tmp/git-repository && git push --force"
      environment:
          GIT_SSH_COMMAND: 'ssh -i /tmp/.rkt-git.rsa'
  always:
      - include_tasks: includes/finally.git-clone.yaml
        tags: ['git', 'git_all']

      - name: Delete repository directory
        tags: ['git', 'git_all']
        file:
            path: /tmp/git-repository
            state: absent
