- name: Check if Sealed Secrets was already configred
  stat: path=/tmp/git-repository/root/vault.yaml.j2
  register: vault_configured

- when: '"git_vault" in ansible_run_tags or not vault_configured.stat.exists'
  block:
      - name: Create Vault definition
        template:
            src: "repository/{{ item }}"
            dest: /tmp/git-repository/{{ item | regex_replace('\.j2$', '') }}
        with_items:
            - root/vault.yaml.j2
