- name: Check if README is present
  stat: path=/tmp/git-repository/README.md
  register: readme_created

- when: 'not readme_created.stat.exists'
  block:
      - name: Copy README.md
        tags: ['git_all']
        template:
            src: "repository/{{ item }}"
            dest: /tmp/git-repository/{{ item | regex_replace('\.j2$', '') }}
        with_items:
            - README.md
