- name: Check if ArgoCD was already placed in repository
  stat: path=/tmp/git-repository/bootstrap/argocd/kustomization.yaml
  register: argocd_configured

- when: '"git_argocd" in ansible_run_tags or not argocd_configured.stat.exists'
  block:
      - name: Place ArgoCD definition inside repository
        template:
            src: "repository/bootstrap/argocd/{{ item }}"
            dest: /tmp/git-repository/bootstrap/argocd{{ item | regex_replace('\.j2$', '') }}
        with_items:
            - kustomization.yaml.j2
            - argocd-repo-server.yaml
            - argocd-redis.yaml
            - argocd-cmd-params-cm.yaml
            - argocd-applicationset-controller.yaml
            - argocd-application-controller.yaml
            - README.md
