#
# Sealed Secrets is not managed by ArgoCD. It needs to be installed before GIT repository is created,
# but creation of a repository is before ArgoCD. In ArgoCD we already depend on Sealed Secrets.
#

- become: yes
  become_user: root
  environment:
      KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  block:
      - name: Render /tmp/argocd-initial-values.yaml
        template:
            src: tmp/sealed-secrets-initial-values.yaml.j2
            dest: /tmp/sealed-secrets-initial-values.yaml

      - name: Install Bitnami Sealed Secrets using Helm
        shell: |
            helm upgrade --install sealed-secrets sealed-secrets --repo https://bitnami-labs.github.io/sealed-secrets/ \
                --create-namespace \
                --values /tmp/sealed-secrets-initial-values.yaml \
                --namespace {{ secrets_namespace }} \
                --version={{ secrets_version }} \
                --wait

      - name: Save certificate to temporary directory
        shell: "curl -vvv \"http://$(kubectl get service/sealed-secrets -n {{ secrets_namespace }} -o jsonpath='{.spec.clusterIP}'):8080/v1/cert.pem\" -o /etc/rancher/k3s/sealed-secrets.cert.pem"
        retries: 25
        delay: 3
        register: vault_sync
        until: vault_sync.rc == 0

      - name: Fetch certificate
        fetch:
            src: "/etc/rancher/k3s/sealed-secrets.cert.pem"
            dest: "artifacts/sealed-secrets.cert.pem"
            flat: true
