- name: Download crun binary
  get_url:
      url: https://github.com/containers/crun/releases/download/{{ crun_version }}/crun-{{ crun_version }}-linux-amd64
      dest: /usr/local/bin/crun
      mode: "u+rwx,g+rx,o+rx"

- name: Download gVisor runsc binary
  get_url:
      url: https://storage.googleapis.com/gvisor/releases/release/latest/x86_64/runsc
      dest: /usr/local/bin/runsc
      mode: "u+rwx,g+rx,o+rx"

- name: Download gVisor shim binary
  get_url:
      url: https://storage.googleapis.com/gvisor/releases/release/latest/x86_64/containerd-shim-runsc-v1
      dest: /usr/local/bin/containerd-shim-runsc-v1
      mode: "u+rwx,g+rx,o+rx"

# Reconfigure containerd
- name: Create build directory
  file:
      path: /tmp/gvisor-config-build
      state: directory

- name: Make sure the containerd directory exists
  file:
      path: /var/lib/rancher/k3s/agent/etc/containerd/
      state: directory

- name: Configure gVisor shim
  template:
      src: etc/containerd/runsc.toml
      dest: /var/lib/rancher/k3s/agent/etc/containerd/runsc.toml

- name: Register in containerd configuration
  copy:
      src: files/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl
      dest: /var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl

# End of containerd reconfiguration
