- name: Create temporary directory for git repository preparation
  tags: ['git', 'git_all']
  file:
      path: /tmp/git-repository
      state: directory

- name: Write GIT configuration key
  when: cluster_git_repository.deployment_time_access_key is defined and cluster_git_repository.deployment_time_access_key
  tags: ['git', 'git_all']
  copy:
      content: "{{ cluster_git_repository.deployment_time_access_key }}"
      dest: "/tmp/.rkt-git.rsa"
      mode: "0600"

- name: Clone (GIT+SSH)
  when: "'git@' in cluster_git_repository.remote"
  tags: ['git', 'git_all']
  git:
      key_file: "/tmp/.rkt-git.rsa"
      repo: "{{ cluster_git_repository.remote }}"
      version: "{{ cluster_git_repository.branch }}"
      dest: /tmp/git-repository
      clone: yes
      update: yes
      accept_hostkey: yes
      force: yes
  environment:
      GIT_ASKPASS: "/usr/bin/true"

- when: "'git@' not in cluster_git_repository.remote"
  block:
    - name: Add credentials
      set_fact:
          remote_with_credentials: "{{ cluster_git_repository.remote | replace('https://', 'https://'+cluster_git_repository.deployment_time_user+':'+cluster_git_repository.deployment_time_password+'@')  | replace('http://', 'http://'+cluster_git_repository.deployment_time_user+':'+cluster_git_repository.deployment_time_password+'@') }}"

    - name: Clone (GIT+HTTPS)
      tags: ['git', 'git_all']
      git:
          repo: "{{ remote_with_credentials }}"
          version: "{{ cluster_git_repository.branch }}"
          dest: /tmp/git-repository
          clone: yes
          update: yes
          accept_hostkey: yes
          force: yes
