- name: Create temporary directory for git repository preparation
  tags: ['git', 'git_all']
  file:
      path: /tmp/git-repository
      state: directory

- name: Write GIT configuration key
  tags: ['git', 'git_all']
  copy:
      content: "{{ cluster_git_repository.deployment_time_access_key }}"
      dest: "/tmp/.rkt-git.rsa"
      mode: "0600"

- name: Clone
  tags: ['git', 'git_all']
  git:
      key_file: "/tmp/.rkt-git.rsa"
      repo: "{{ cluster_git_repository.remote }}"
      version: "{{ cluster_git_repository.branch }}"
      dest: /tmp/git-repository
      clone: yes
      update: yes
      accept_hostkey: yes
      force: yes
  environment:
      GIT_ASKPASS: "/usr/bin/true"
