- name: Check if AppProject was already created
  tags: ['git', 'git_all']
  stat: path=/tmp/git-repository/{{ item | regex_replace('\.j2$', '') }}
  register: project_exists

- name: Copy AppProject
  tags: ['git', 'git_all']
  template:
      src: "repository/{{ item }}"
      dest: /tmp/git-repository/{{ item | regex_replace('\.j2$', '') }}
  when: '"git_projects" in ansible_run_tags or not project_exists.stat.exists'
