- become: yes
  become_user: root
  block:
      - name: Check if version was already downloaded
        stat:
            path: "/usr/local/bin/vpncloud_{{ vpn_cloud_version }}_static_amd64"
        register: binary_path

      - name: Download specified version from Github releases
        when: not binary_path.stat.exists
        get_url:
            url: "https://github.com/dswd/vpncloud/releases/download/v{{ vpn_cloud_version }}/vpncloud_{{ vpn_cloud_version }}_static_amd64"
            dest: "/usr/local/bin/vpncloud_{{ vpn_cloud_version }}_static_amd64"
            mode: "u+rwx,g+rx,o+rx"
            owner: root
            group: root

      - name: Make a symbolic link
        file:
            src: "/usr/local/bin/vpncloud_{{ vpn_cloud_version }}_static_amd64"
            dest: "/usr/bin/vpncloud"
            state: link
            mode: "u+rwx,g+rx,o+rx"
            owner: root
            group: root
