- become: yes
  become_user: root
  block:
      - name: Make sure /etc/riotkit directory exists
        file:
            path: /etc/riotkit
            state: directory
            mode: "u+rw,g-r,o-r"
            owner: root
            group: root

      - name: Create VPN configuration from collected local artifact (created on Ansible execution machine by same playbook ran previously on primary node)
        template:
            src: artifacts/vpn-node-template.yaml.j2
            dest: /etc/riotkit/vpn.yaml
            mode: "u+rw,g-r,o-r"
            owner: root
            group: root
