- include: repository.yaml
  tags: repository
  when: node_type == "primary"

- include: tools.yaml
  tags: tools

- include: cluster.primary.yaml
  tags: ['cluster', 'k3s']
  when: node_type == "primary"

- include: cluster.compute.yaml
  tags: ['cluster', 'k3s']
  when: node_type == "compute"

- include: argocd.yaml
  tags: argocd
  when: node_type == "primary"
